export const EVENTS = [
  'click',
  'pointerdown',
  'pointermove',
  'pointerup',
  'pointerleave',
  'doubletap',
  'pinchin',
  'pinchout',
  'pinchstart',
  'pinchmove',
  'pinchend',
  'pinchcancel',
  'rotatestart',
  'rotatemove',
  'rotateend',
  'rotatecancel',
  'panstart',
  'panmove',
  'panend',
  'pancancel',
  'panup',
  'pandown',
  'panleft',
  'panright',
  'swipe',
  'swipeleft',
  'swiperight',
  'swipeup',
  'swipedown'
];

export const INITIAL_OPTIONS = {
  click: true,
  doubletap: true,
  pointermove: true,
  pointerleave: true,
  pinchstart: true,
  pinchmove: true,
  pinchend: true,
  rotatestart: true,
  rotatemove: true,
  rotateend: true,
  panstart: true,
  panmove: true,
  panend: true
};
